Feat/treasury vester
vexchange/governance-frontend pull request #27
Opened 2022-02-01 02:34 UTC by hochbruj

https://trello.com/c/aDDiN0F7

2022-02-04 23:11 UTC, xenide commented
Thanks for the good work, looks pretty good. Some further improvements we can make:

1. As spoken, please review if we really need the additional `BigNumber` library as it seems that the existing `ethers.BigNumber` implementation can handle the operations you're doing. You can refer to other instances of use of `BigNumber` within the same repo. 

2. When the user declines the transaction on sync2, currently it shows up as an unhandled error. We should handle it with a `catch` clause, and just print it to the console or something, but it shouldn't crash like this. 
<img width="1024" alt="Screenshot 2022-02-05 at 6 58 36 AM" src="https://user-images.githubusercontent.com/5846427/152614526-84ec787b-1a29-4db9-9322-87059ebdc3cb.png">
 
3. The contract address of the TreasuryVester for the DAO should be `0x8Fc3737CF99984961b43f86ce5C82cfaa4B49657`. Please verify again with the output in the governance repo. The current address you have is the vester for proxima. 

Thanks

2022-02-04 23:23 UTC, xenide requested changes

2022-02-04 23:23 UTC, xenide commented on utils/constants.js
>      // Just a placeholder, this address does not contain a contract
Can we remove this comment now that this address actually has a contract?

2022-02-07 13:30 UTC, xenide commented on state/assets.js
>              } else {
Can we start the else on a newline?

2022-02-07 13:31 UTC, xenide commented
Just have that one last comment. Besides that, everything looks good, thanks 👍

2022-02-07 18:59 UTC, KennethAshley approved these changes
Alex commented on the changes I'd make so I'm gonna approve this! Good code!

2022-02-09 02:42 UTC, hochbruj commented on state/assets.js
>              } else {
done

2022-02-09 02:42 UTC, merged