Fix/decimals for uint256
vexchange/governance-frontend pull request #29
Opened 2022-02-03 14:27 UTC by xenide

# Why?
- In the original fish.vote code base, it assumed that all uint256 numbers were 18 decimal based. This is incompatible for our uses as some uint256 uses do not have decimals 
- This will result in the first proposal failing to execute, as the `swapFee` is a non-sensical large number
- I was supposed to catch this during testing 

# What changed?
- refactored the parsing of numbers during proposal creation, to generate the correct numerical value 
- refactored the parsing of numbers during proposal viewing, to show the corresponding human readable number

2022-02-03 15:00 UTC, andersonaguiar requested changes

2022-02-03 15:00 UTC, andersonaguiar commented on state/governance.js
> +    console.log(calldataRaw);
Should we remove this?

2022-02-03 15:00 UTC, andersonaguiar commented on state/governance.js
> +    console.log(calldataBytes);
same

2022-02-03 15:30 UTC, OliverNChalk approved these changes
config looks good to me, didnt look deeply in the front-end logic

2022-02-03 23:29 UTC, KennethAshley approved these changes
looks good but console logs

2022-02-04 00:18 UTC, xenide commented on state/governance.js
> +    console.log(calldataRaw);
fixed, thanks

2022-02-04 00:18 UTC, xenide commented on state/governance.js
> +    console.log(calldataBytes);
fixed

2022-02-04 01:25 UTC, merged